import Head from 'next/head'
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Zetaweb</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero heading='Zeta OÜ' message='Kodulehed, e-kaubandus, IT taristu - oleme multifunktsionaalne ettevõte. Meie peamisteks tegevusaladeks on serverimajutus, seadmete paigaldus, veebi- ja mobiilirakenduste arendus.' />
    </div>
  )
}
